package com.example.demo.exception;

public enum ErrorCode {
	USER_NOT_FOUND,
	TRANSFER_CREATE_FAILED,
	TRANSFER_STATE_UNCERTAIN,
	TRANSFER_MQ_ERROR,
	TRANSFER_ROW_MISSING,
	TRANSFER_NOT_FOUND,
	TRANSFER_ALREADY_CANCELLED,
	TRANSFER_ALREADY_SETTLED,
	CANCEL_WINDOW_EXPIRED,
	TRANSFER_NOT_PENDING,
	INVALID_TRANSFER,
	USER_ALREADY_EXISTS,
	VALIDATION_ERROR,
}
